capital: 1000000
commission: 0.0004
data_path: data
results_dir: results
database: results/history.db

data:
  interval: hour
  history_days: 90
  extra_symbols:
    - USD000UTSTOM
    - FXRL
  universe:
    enabled: true
    classes:
      - equity
      - etf
      - bond
      - futures
      - fx
    tiers:
      - tier1_2
      - tier3
    exclude: []
    include_figi: true
    export: true
    export_path: data/universe.csv

# Параметры маржинальной торговли для бэктестов и живого режима.
margin:
  max_leverage: 2.0
  borrow_rate_pct: 12.0
  short_borrow_rate_pct: 15.0
  financing_periods_per_year: 252

# Режим работы: ``live`` (боевой), ``virtual`` (без отправки заявок)
# или ``sandbox`` (песочница Tinkoff).
trade_mode: sandbox

# Параметры Telegram. Значения рекомендуется задавать через переменные
# окружения, используя синтаксис ``${VAR}``.
telegram:
  token: ${TELEGRAM_TOKEN}
  chat_id: ${TELEGRAM_CHAT_ID}

  # Разрешённые пользователи Telegram (ID). Если список пуст, команды
  # будут игнорироваться.
  allowed_users: []

# Стратегии: имя → класс и параметры.
# ``symbols`` определяет тикеры для живого наблюдения.
strategies:
  sma_strategy:
    class: SMAStrategy
    module: sma
    params:
      short_window: 5
      long_window: 20
    symbols:
      - SBER
      - GAZP
  ml_predict:
    class: MLPredictStrategy
    module: ml_predict
    params:
      window: 30
      model: RandomForest
    symbols:
      - LKOH
      - ROSN
  supertrend:
    class: SuperTrendStrategy
    module: supertrend
    params:
      period: 10
      multiplier: 3.0
    symbols:
      - TATN
      - MTSS
  atr_stop:
    class: ATRStopStrategy
    module: atr_stop
    params:
      atr_period: 14
      multiplier: 2.0
    symbols:
      - AFLT
      - MGNT
  pair_trading:
    class: PairTradingStrategy
    module: pair_trading
    params:
      lookback: 60
      entry_threshold: 2.0
      exit_threshold: 0.5
    symbols:
      - SBER
      - GAZP

  # Дополнительные стратегии для демонстрации возможностей.
  rsi:
    class: RSIStrategy
    module: rsi
    params:
      period: 14
      lower: 30.0
      upper: 70.0
    symbols:
      - SBER
      - GAZP
  bollinger_bands:
    class: BollingerBandsStrategy
    module: bollinger_bands
    params:
      window: 20
      multiplier: 2.0
    symbols:
      - MGNT
      - AFLT
  arbitrage:
    class: ArbitrageStrategy
    module: arbitrage
    params:
      lookback: 20
      entry_threshold: 2.0
      exit_threshold: 0.5
    symbols:
      - SBER
      - GAZP
  news_sentiment:
    class: NewsSentimentStrategy
    module: news_sentiment
    params: {}
    symbols:
      - ROSN
      - TATN
  lstm_predict:
    class: LSTMPredictStrategy
    module: lstm_predict
    params:
      window: 30
    symbols:
      - GAZP
      - LKOH

# Настройки риск-менеджера. Ключи соответствуют параметрам ``RiskManager``.
risk:
  max_drawdown_pct: 0.2
  max_daily_loss_pct: 0.1
  max_position_pct: 0.2
  per_trade_risk_pct: 0.02
  stop_loss_pct: 0.05
  take_profit_pct: 0.1
  max_positions: 5
  allow_short: true
  max_leverage: 2.0
  borrow_rate_pct: 12.0
  short_borrow_rate_pct: 15.0
  financing_periods_per_year: 252
  monitor_interval: 10
  journal:
    enabled: true
  instrument_classes:
    SBER: equity
    GAZP: equity
    FXRL: etf
    USD000UTSTOM: fx
  instrument_limits:
    SBER:
      max_position_pct: 0.25
      max_lots: 200
    USD000UTSTOM:
      max_position_pct: 0.15
  asset_class_limits:
    equity:
      max_exposure_pct: 0.75
    fx:
      max_exposure_pct: 0.3

# Планировщик задач (формат cron).
schedule:
  daily_backtest:
    func: "moex_bot.run_backtests.main"  # основной бэктестовый сценарий
    cron: "0 8 * * *"
  live_trading:
    func: "moex_bot.run_live.main"
    cron: "*/1 * * * *"  # каждую минуту
  data_update:
    func: "moex_bot.update_data.run_scheduled_update"
    cron: "30 6 * * 1-5"

# Целевые веса стратегий (в сумме 1.0).
portfolio:
  target_allocations:
    sma_strategy: 0.15
    ml_predict: 0.15
    supertrend: 0.15
    atr_stop: 0.15
    pair_trading: 0.15
    rsi: 0.05
    bollinger_bands: 0.05
    arbitrage: 0.05
    news_sentiment: 0.05
    lstm_predict: 0.05

# Автоподбор стратегий и гипероптимизация.
auto_selector:
  enabled: true
  top_n: 5
  min_sharpe: 1.0
  max_drawdown_pct: 0.2
  diversify_by: file
  top_per_group: 1
  weight_metric: sharpe
  hyperopt:
    enabled: false

# HTTP-сервер FastAPI/Dash. Можно переопределить через ``MOEX_API_HOST``
# и ``MOEX_API_PORT``.
server:
  host: 127.0.0.1
  port: 8000

# Настройки брокерского API Tinkoff. ``sandbox`` включает песочницу.
tinkoff:
  # Токен боевого режима (обязателен для live).
  token: ${TINKOFF_TOKEN}
  # Боевой счёт.
  account_id: ${TINKOFF_ACCOUNT_ID}
  # Флаг использования песочницы (true/false).
  sandbox: ${TINKOFF_SANDBOX}
  # Токен песочницы (при ``sandbox=true``).
  sandbox_token: ${TINKOFF_SANDBOX_TOKEN}
  # Счёт песочницы.
  account_id_sandbox: ${TINKOFF_ACCOUNT_ID_SANDBOX}

