name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black pytest
          # install project in editable mode with optional extras for reports
          pip install -e .
      - name: Lint with ruff
        run: ruff .
      - name: Check code format with black
        run: black --check .
      - name: Run unit tests
        env:
          PYTHONPATH: .
        run: pytest -q